### ISSUE TITLE
refactor: emissions-elt-demo to climatrax-frontend

### ISSUE THREAD

**Issue by shon-button** [button-inc/climatetrax-frontend#1]
As a developer 
I want to refactor emissions-elt-demo codebase into the climatetrax-frontend codebase 
so that I can implement development choices made by the Innovation Team such as:
implement local Kubernetes using Cloud Code with k8s minicube for dev-prod environment parity

## Acceptance Criteria:
- [x] The refactored codebase should be built with Next.js 13 latest and follow best practices for Next.js development.
- [x] The application should be able to run on Cloud Code Kubernetes without any errors or issues.
- [x] The refactored code should be thoroughly tested and validated to ensure proper functionality.

## Tasks:

Set up the Development Environment:
- [x] Install Node.js 
- [x] Install pnpm package manager
- [x] Install Visual Studio Code (VSC) 
- [x] Install VSC extension: Cloud Code

Create a New Next.js Project:
- [x] Use the Next.js CLI or a template to generate a new Next.js project with Next.js 13.
- [x] Set up  best practice project structure 

Configure the project to run in local Kubernetes:
[Configure ClimateTrax for k8s local dev](https://github.com/button-inc/emissions-elt-demo/issues/228#top)](https://github.com/button-inc/emissions-elt-demo/issues/228)
|---- .vscode
| └---- launch.json
|---- kubernetes-manifests
| |---nextjs-app-deployment.yaml
| |---- nextjs-app-service.yaml
| |---- Dockerfile
| └---- package.json
└---- skaffold.yaml
